apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l7tveiuws-python 
  janus-idp.io/tekton: l7tveiuws-python
  backstage.io/kubernetes-id: l7tveiuws-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l7tveiuws-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml